### PR TITLE
Fix: Warning seed phrase bug

### PR DESCRIPTION
**Pull request by saurabh391**
[ Done ] Warning: Address not saved by seed phrase #270

### CODE REVIEW

**Review by monstrobishi — CHANGES_REQUESTED** [review]
I don't think this will fix the issue unfortunately, and we should avoid calling `getNewAddress` everywhere, we are generating new wallet addresses for no reason. `rpcClient.getNewAddress` should only be called when the user specifically wants to create a new address!

**Comment by saurabh391** [comment]
> I don't think this will fix the issue unfortunately, and we should avoid calling `getNewAddress` everywhere, we are generating new wallet addresses for no reason. `rpcClient.getNewAddress` should only be called when the user specifically wants to create a new address!

The issue was it was checking for the hdsseedkey in the local storage and start comparing from that but sometimes the key belonged to old wallet. Let me look for something other than getnewaddress

**Comment by monstrobishi** [comment]
Yes please, I created 2 more tickets where I found getNewAddress is being used when it shouldn't be used, I will assign you

**Comment by monstrobishi** [comment]
@saurabh391 please use getwalletinfo RPC call and compare with hdseedid attribute in the JSON response

**Comment by monstrobishi** [comment]
Remove anything related to PersistantStorage, we do not want to use PersistantStorage here, just directly compare the hdseedid inside getaddressinfo with the hdseedid into getwalletinfo

**Comment by monstrobishi** [comment]
looks good will merge

**Pull request merged**
