### PR TITLE
fix: shutdown node issue

### PR DESCRIPTION
**Pull request by thedoublejay**

### CODE REVIEW

**Comment by monstrobishi** [comment]
Can we increase the timeout to 60 seconds for slower pcs

**Comment by thedoublejay** [comment]
> Can we increase the timeout to 60 seconds for slower pcs

Hmm it's already 30 minutes. I can adjust the time, which one you prefer?

**Comment by monstrobishi** [comment]
Oh then that's too long, let's make it 5 minutes

**Comment by thedoublejay** [comment]
Updated @monstrobishi

**Pull request merged**
