### PR TITLE
chore: bump app and node packages

### PR DESCRIPTION
**Pull request by thedoublejay**

### CODE REVIEW

**Comment by thedoublejay** [comment]
@monstrobishi build is failing because new node is not yet present. Let's re-run it later

**Review by sergejmueller — COMMENTED** [review]
"connectedToPeers": "Verbunden mit %{peers} Peers",
@thedoublejay Is `Peers` more understandable as `Knoten`? Maybe `Netzwerkknoten`?

**Comment by thedoublejay** [comment]
> "connectedToPeers": "Verbunden mit %{peers} Peers",
> @thedoublejay Is `Peers` more understandable as `Knoten`? Maybe `Netzwerkknoten`?

@sergejmueller It was requested by our german translator. Let me check with him `Netzwerkknoten` is ok.

**Comment by sergejmueller** [comment]
@thedoublejay He doesn't care about all the spelling mistakes ([1](https://github.com/DeFiCh/app/commit/49e99abefe590aea262553fb90b1e064e53d2991#diff-a8eb4cf456468f0c4ab5876a27980c7d3b9e9fc58c3123f2f779ea00ea878652), [2](https://github.com/DeFiCh/app/commit/30cd6f24ebf6aec1f9a7f7a6fba08333dd462478#diff-a8eb4cf456468f0c4ab5876a27980c7d3b9e9fc58c3123f2f779ea00ea878652), [3](https://github.com/DeFiCh/app/commit/be22d0afd171c126e054e16154e9742e6bb642b1#diff-a8eb4cf456468f0c4ab5876a27980c7d3b9e9fc58c3123f2f779ea00ea878652)) and wants to correct this one thing? It's ok.

**Comment by thedoublejay** [comment]
> @thedoublejay He doesn't care about all the spelling mistakes ([1](https://github.com/DeFiCh/app/commit/49e99abefe590aea262553fb90b1e064e53d2991#diff-a8eb4cf456468f0c4ab5876a27980c7d3b9e9fc58c3123f2f779ea00ea878652), [2](https://github.com/DeFiCh/app/commit/30cd6f24ebf6aec1f9a7f7a6fba08333dd462478#diff-a8eb4cf456468f0c4ab5876a27980c7d3b9e9fc58c3123f2f779ea00ea878652), [3](https://github.com/DeFiCh/app/commit/be22d0afd171c126e054e16154e9742e6bb642b1#diff-a8eb4cf456468f0c4ab5876a27980c7d3b9e9fc58c3123f2f779ea00ea878652)) and wants to correct this one thing? It's ok.

@sergejmueller It's not that he doesn't care. He might have overlooked it. Anyway, he replied and he prefers using "peers" so we can keep it like this.

**Pull request merged**
