### PR TITLE
fix: issue on console params

### PR DESCRIPTION
**Pull request by thedoublejay**

### CODE REVIEW

**Comment by monstrobishi** [comment]
No that's not quite right, it's just converting BigNumber to Number here. UZyn's suggestion was to first check if the BigNumber is an integer only then convert it to Number

**Comment by thedoublejay** [comment]
> gNumber to Number here. UZyn's suggestion was to first check if the BigNumber is an integer only then convert it to Number

It's already handled. The condition is to check if the BN isNaN. If yes, it will return the original params. Otherwise, it will convert it to Number

**Comment by monstrobishi** [comment]
We still want to pass in BigNumber if it's a number, this is for accuracy reasons for commands like sendtoaddress. `isNAN` still still return false if the BigNumber was something like 1000000.00000123 in which case converting to Number would result in precision loss, we only want to convert if the BigNumber has no decimal places

**Comment by thedoublejay** [comment]
> We still want to pass in BigNumber if it's a number, this is for accuracy reasons for commands like sendtoaddress. `isNAN` still still return false if the BigNumber was something like 1000000.00000123 in which case converting to Number would result in precision loss, we only want to convert if the BigNumber has no decimal places

ahhh ok ok my bad. Let me update it

**Comment by thedoublejay** [comment]
Updated @monstrobishi

**Comment by monstrobishi** [comment]
Can we use toFixed(8) instead of toString just incase

**Comment by thedoublejay** [comment]
> Can we use toFixed(8) instead of toString just incase

Sure give me a sec

**Comment by thedoublejay** [comment]
Updated @monstrobishi. I tested it as well with more than 8 decimal places. It doesn't work with RPC. It should be only 8 decimal places I think

**Comment by monstrobishi** [comment]
Yep that's fine

**Comment by monstrobishi** [comment]
Merging

**Pull request merged**
