### PR TITLE
Fix: Optimized images

### PR DESCRIPTION
**Pull request by sergejmueller**
* Lossless optimizing for SVG and PNG images

### CODE REVIEW

**Comment by thedoublejay** [comment]
Hi @sergejmueller, I think this step is already handled by Webpack. You can check this file - https://github.com/DeFiCh/app/blob/master/webapp/webpack/plugins/pluginImages.js

**Comment by sergejmueller** [comment]
@thedoublejay I know. I think the sources should be kept clean, then the build process has less to do and is faster.

But if you think that's unnecessary, we can close the PR.

**Comment by thedoublejay** [comment]
@sergejmueller I think it should be ok. Thanks for your suggestion. You can close the PR.

**Comment by sergejmueller** [comment]
Unnecessary, closed.

**Pull request closed without merging**
