### PR TITLE
feature: hardware ledger wallet

### PR DESCRIPTION
**Pull request by DeFiDev**
Added support of ledger wallet

### CODE REVIEW

**Review by fuxingloh — CHANGES_REQUESTED** [review]
please squash commits, there are 208 of them

**Comment by monstrobishi** [comment]
@DeFiDev can you resolve conflicts

**Comment by thedoublejay** [comment]
@DeFiDev can we remove this file? `webapp/webpack.config.js ` it's an empty file

**Comment by thedoublejay** [comment]
@DeFiDev  error in codacy - LedgerReceivePage/LedgerReceovePage.module.scss missing EOL 
`Unexpected missing end-of-source newline (no-missing-end-of-source-newline)`. Also Typo on the filename - should be `LedgerReceivePage.module.scss`

**Pull request closed without merging**
